package com.tian.demo.model;

import java.io.Serializable;

public class Users implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.name
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.password
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.sex
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.nick_name
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	private String nickName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.name
	 * @return  the value of users.name
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.name
	 * @param name  the value for users.name
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.password
	 * @return  the value of users.password
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.password
	 * @param password  the value for users.password
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.sex
	 * @return  the value of users.sex
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.sex
	 * @param sex  the value for users.sex
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.nick_name
	 * @return  the value of users.nick_name
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.nick_name
	 * @param nickName  the value for users.nick_name
	 * @mbg.generated  Sun Jul 30 10:36:43 CST 2017
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName == null ? null : nickName.trim();
	}
}